[package]
name = "rust_ann"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = { version = "0.15", features = ["serde"] }
polars = { version = "0.44.2", features = ["lazy", "ndarray"] }
rand = "0.8.5"
