[package]
name = "rust_ann"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
env_logger = "0.11.5"
log = "0.4.22"
ndarray = { version = "0.15", features = ["serde"] }
polars = { version = "0.44.2", features = ["lazy", "ndarray"] }
rand = "0.8.5"
